### PR TITLE
Fix "no output" issue

### PR DESCRIPTION
**Pull request by arvaki**
Tested on macOS Catalina 10.15 Beta 7 (19A546d).

### CODE REVIEW

**Comment by arvaki** [comment]
@davedelong what do you think about the changes?

**Review by MAX-POLKOVNIK — APPROVED** [review]
Check changes. Output files now exists

**Comment by rob-dodson** [comment]
Please merge this pr. Currently the utility does not work without this fix.

**Comment by davedelong** [comment]
Finally getting a chance to look at this...

I'm thinking that I'd like to keep both branches of the code in place, and then conditionally pick the glyph initializer based on the number of columns found in the CSV.

@kireev165 would you mind if I pull your commits in, add in the branch with the old initializer, and then push that? I think I'd need to close the PR to do that.

**Comment by arvaki** [comment]
> would you mind if I pull your commits in, add in the branch with the old initializer, and then push that? I think I'd need to close the PR to do that.

That's ok.

> I'm thinking that I'd like to keep both branches of the code in place, and then conditionally pick the glyph initializer based on the number of columns found in the CSV.

I just thought it is unnecessary to support beta versions.

**Comment by davedelong** [comment]
Alright, I think this is all set; it looks good on my end. Please check it out and let me know if it needs any refinement. 🙇

**Pull request merged**
